#!/bin/bash
set -euo pipefail

# verify_clean_tree_allowlist.sh
#
# Canonical dirty-tree gate: ensures git working tree contains ONLY
# allowed changes. Run from any directory; uses git to find repo root.
#
# Allowlist:
#  - atlassian/forge-app/docs/production/* (audit documentation)
#  - atlassian/forge-app/tools/production/* (new audit gates)
#  - atlassian/forge-app/tests/production/* (audit tests)
#  - atlassian/forge-app/src/storage_debug.ts (EXPLICIT EXCEPTION: admin debug endpoint fix)
#  - atlassian/forge-app/tools/verify_dist_invoke_allowlist.sh (EXPLICIT EXCEPTION: invoke allowlist fix)
#
# Exit 0: All dirty files within allowlist
# Exit 1: Files outside allowlist detected (fail-closed)

# Find repo root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

echo "[CLEAN_TREE] Verifying dirty working tree against allowlist..."

# Get all dirty files (modified + untracked)
DIRTY_FILES=$(git status --porcelain | grep -v "^??" | awk '{print $NF}' | sort || true)
UNTRACKED_FILES=$(git status --porcelain | grep "^??" | awk '{print $NF}' | sort || true)

# Combine into single list
ALL_DIRTY="$DIRTY_FILES"
if [[ -n "$UNTRACKED_FILES" ]]; then
  if [[ -n "$ALL_DIRTY" ]]; then
    ALL_DIRTY="$(echo -e "$ALL_DIRTY\n$UNTRACKED_FILES" | sort)"
  else
    ALL_DIRTY="$UNTRACKED_FILES"
  fi
fi

# If no dirty files, pass immediately
if [[ -z "$ALL_DIRTY" ]]; then
  echo "[CLEAN_TREE] ✓ PASS: Working tree is clean"
  exit 0
fi

echo "[CLEAN_TREE] Checking dirty files against allowlist..."

# Define allowlist (exact paths + glob patterns)
# Note: paths are relative to repository root (/workspaces/Firsttry), not cwd
ALLOW_PATTERNS=(
  "atlassian/forge-app/docs/production/*"
  "atlassian/forge-app/tests/production/*"
  "atlassian/forge-app/tools/production/*"
)

# Define explicit exceptions (exact file paths only)
# Minimal set: only files that have runtime impact and cannot be generated by build
EXPLICIT_EXCEPTIONS=(
  "atlassian/forge-app/src/storage_debug.ts"
  "atlassian/forge-app/tools/verify_dist_invoke_allowlist.sh"
)

# Check each dirty file
VIOLATIONS=0
while IFS= read -r FILE; do
  [[ -z "$FILE" ]] && continue
  
  IS_ALLOWED=0
  
  # Check against allowlist patterns (glob match)
  for PATTERN in "${ALLOW_PATTERNS[@]}"; do
    if [[ "$FILE" == $PATTERN || "$FILE"/ == $PATTERN ]]; then
      IS_ALLOWED=1
      break
    fi
  done
  
  # Check against explicit exceptions (exact match for files or parent match for directories)
  if (( IS_ALLOWED == 0 )); then
    for EXCEPTION in "${EXPLICIT_EXCEPTIONS[@]}"; do
      # Exact match (for files)
      if [[ "$FILE" == "$EXCEPTION" ]]; then
        IS_ALLOWED=1
        echo "  [EXCEPTION] $FILE (explicit allowance)"
        break
      fi
      # Parent match (for directory contents)
      if [[ "$FILE" == "$EXCEPTION"/* ]]; then
        IS_ALLOWED=1
        echo "  [EXCEPTION] $FILE (within excepted directory)"
        break
      fi
    done
  fi
  
  # Report result
  if (( IS_ALLOWED == 1 )); then
    [[ "$FILE" != "${FILE%/*}"/* ]] && echo "  [OK] $FILE"
  else
    echo "  [VIOLATION] $FILE"
    ((VIOLATIONS++))
  fi
done <<< "$ALL_DIRTY"

# Fail-closed exit
if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[CLEAN_TREE] ✗ FAIL: $VIOLATIONS file(s) outside allowlist"
  echo ""
  echo "Allowlist:"
  for PATTERN in "${ALLOW_PATTERNS[@]}"; do
    echo "  - $PATTERN"
  done
  echo ""
  echo "Explicit exceptions:"
  for EXCEPTION in "${EXPLICIT_EXCEPTIONS[@]}"; do
    echo "  + $EXCEPTION"
  done
  exit 1
fi

echo "[CLEAN_TREE] ✓ PASS: All dirty files within allowlist"
exit 0
