#!/usr/bin/env node
/**
 * gen_ui_build_meta.mjs
 *
 * CONTRACT SOURCE OF TRUTH: Reads UI_GIT_SHA from tools/.build_meta.json
 * (generated by build_meta.mjs which uses git rev-parse HEAD)
 * 
 * Generates ui_build_meta.ts with immutable UI build identifiers.
 * Output: atlassian/forge-app/src/gadget-ui/src/ui_build_meta.ts
 * 
 * CRITICAL: Must use the SAME UI_GIT_SHA value as build_meta.mjs computed.
 * This ensures consistency across JSON (Vite) and TS (runtime) sources.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function readBuildMeta() {
  try {
    const buildMetaPath = path.join(__dirname, '.build_meta.json');
    if (!fs.existsSync(buildMetaPath)) {
      console.error('[FATAL_UI_GIT_SHA_MISSING] tools/.build_meta.json not found');
      console.error('  (build_meta.mjs should have run first)');
      process.exit(1);
    }
    const content = fs.readFileSync(buildMetaPath, 'utf8');
    const meta = JSON.parse(content);
    
    if (!meta.UI_GIT_SHA || meta.UI_GIT_SHA.length !== 40) {
      console.error(`[FATAL_UI_GIT_SHA_MISSING] UI_GIT_SHA invalid in .build_meta.json: got "${meta.UI_GIT_SHA}" (${meta.UI_GIT_SHA ? meta.UI_GIT_SHA.length : 0} chars)`);
      process.exit(1);
    }
    
    if (!meta.FT_BUILD_TIME_UTC) {
      console.error('[FATAL_UI_GIT_SHA_MISSING] FT_BUILD_TIME_UTC missing from .build_meta.json');
      process.exit(1);
    }
    
    return meta;
  } catch (e) {
    console.error('[FATAL_UI_GIT_SHA_MISSING] Failed to read build metadata:', e.message);
    process.exit(1);
  }
}

function main() {
  const meta = readBuildMeta();
  const uiGitSha = meta.UI_GIT_SHA;
  const timeUtc = meta.FT_BUILD_TIME_UTC;

  // Ensure output directory exists
  // Script runs from atlassian/forge-app directory
  const outputDir = path.join(process.cwd(), 'src/gadget-ui/src');
  const outputFile = path.join(outputDir, 'ui_build_meta.ts');

  if (!fs.existsSync(outputDir)) {
    console.error(`ERROR: Output directory not found: ${outputDir}`);
    process.exit(1);
  }

  // Generate file content (CONTRACT: Use UI_GIT_SHA from build_meta.json, not recomputed)
  const content = `/**
 * ui_build_meta.ts - AUTO-GENERATED
 * 
 * Immutable UI build identifiers generated at build time.
 * DO NOT EDIT MANUALLY - regenerated by tools/gen_ui_build_meta.mjs
 * 
 * CRITICAL: These values are sourced from tools/.build_meta.json (build_meta.mjs output),
 * NOT recomputed. This ensures consistency across the entire build pipeline.
 */

export const UI_GIT_SHA = "${uiGitSha}";
export const UI_GIT_TIME = "${timeUtc}";
// Backward compatibility alias for vite.config.ts and main.ts
export const UI_BUILD_TIME_UTC = "${timeUtc}";

/**
 * Dynamic marker for cache-busting: proves the UI was redeployed
 * Format: UI_MARKER_<YYYYMMDDTHHMMSSZ>_<first-7-chars-of-SHA>
 */
function getUTCTimestampForMarker(): string {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(now.getUTCDate()).padStart(2, '0');
  const hh = String(now.getUTCHours()).padStart(2, '0');
  const min = String(now.getUTCMinutes()).padStart(2, '0');
  const ss = String(now.getUTCSeconds()).padStart(2, '0');
  return \`\${yyyy}\${mm}\${dd}T\${hh}\${min}\${ss}Z\`;
}
export const UI_BUILD_MARKER = \`UI_MARKER_\${getUTCTimestampForMarker()}_\${UI_GIT_SHA.substring(0, 7)}\`;
`;

  // Write file
  fs.writeFileSync(outputFile, content, 'utf8');
  console.log(`✓ Generated ${outputFile}`);
  console.log(`  UI_GIT_SHA (40-hex): ${uiGitSha}`);
  console.log(`  UI_GIT_TIME: ${timeUtc}`);
  
  // VERIFICATION: Read back and confirm
  try {
    const written = fs.readFileSync(outputFile, 'utf8');
    if (!written.includes(`export const UI_GIT_SHA = "${uiGitSha}";`)) {
      console.error(`[FATAL_UI_GIT_SHA_MISSING] Verification failed: UI_GIT_SHA not found in generated file`);
      process.exit(1);
    }
    console.log(`✓ Verified: UI_GIT_SHA correctly injected (40-hex)`);
  } catch (e) {
    console.error(`[FATAL_UI_GIT_SHA_MISSING] Verification failed: ${e.message}`);
    process.exit(1);
  }
}

main();
