#!/usr/bin/env node
/**
 * tools/gen_ui_build_identity.mjs
 * 
 * Generates src/gadget-ui/src/buildIdentity.gen.ts with runtime-accessible
 * build metadata: UI_GIT_SHA, UI_BUILD_TIME_UTC, UI_APP_VERSION
 *
 * CRITICAL: This file must be generated during build and NEVER edited manually.
 * The generated file is used by the UI to:
 *   1. Display build identity in footer
 *   2. Compare UI sha vs backend sha for deployment verification
 *   3. Include in error reports and triage bundles
 *
 * Run: node tools/gen_ui_build_identity.mjs
 */

import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.join(__dirname, '..');
const OUTPUT_DIR = path.join(PROJECT_ROOT, 'src/gadget-ui/src/build');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'buildIdentity.gen.ts');

function gitShaFull() {
  try {
    const sha = execSync('git rev-parse HEAD', { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] }).trim();
    if (!sha || sha.length !== 40) {
      console.error(`❌ FATAL: git SHA validation failed. Expected 40 chars, got ${sha ? sha.length : 0}`);
      process.exit(1);
    }
    return sha;
  } catch (e) {
    console.error('❌ FATAL: Failed to get git SHA:', e.message);
    process.exit(1);
  }
}

function gitCommitTimeUtc() {
  try {
    const time = execSync('git show -s --format=%cI HEAD', { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] }).trim();
    if (!time) {
      console.error('❌ FATAL: git commit time is empty');
      process.exit(1);
    }
    // Convert to ISO string without timezone (UTC only)
    const date = new Date(time);
    const isoString = date.toISOString();
    return isoString;
  } catch (e) {
    console.error('❌ FATAL: Failed to get git commit time:', e.message);
    process.exit(1);
  }
}

function getAppVersion() {
  try {
    const pkgPath = path.join(PROJECT_ROOT, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    return pkg.version || '0.0.0-unknown';
  } catch (e) {
    console.error('⚠️  WARNING: Could not read app version from package.json:', e.message);
    return '0.0.0-unknown';
  }
}

function ensureOutputDir() {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log(`✅ Created output directory: ${OUTPUT_DIR}`);
  }
}

function generateBuildIdentity() {
  const uiGitSha = gitShaFull();
  const uiBuildTimeUtc = gitCommitTimeUtc();
  const uiAppVersion = getAppVersion();

  // Extract short SHA (7 chars for UI display)
  const uiGitShaShort = uiGitSha.substring(0, 7);

  const content = `/**
 * AUTOGENERATED FILE: buildIdentity.gen.ts
 * 
 * DO NOT EDIT MANUALLY.
 * Generated by tools/gen_ui_build_identity.mjs during npm run build.
 * 
 * This file exports build identity constants that are used by the UI to:
 * - Display build info in the footer
 * - Verify deployment consistency (UI sha vs backend sha)
 * - Include in error reports and triage bundles
 * - Render visible banners for build mismatches
 */

/**
 * Full 40-character git commit SHA of the UI code
 * Used for cryptographic verification and backend comparison
 */
export const UI_GIT_SHA: string = '${uiGitSha}';

/**
 * Short 7-character git commit SHA for human-readable display
 * Extracted from UI_GIT_SHA for UI footer
 */
export const UI_GIT_SHA_SHORT: string = '${uiGitShaShort}';

/**
 * ISO 8601 UTC timestamp when the UI code was committed
 * Format: YYYY-MM-DDTHH:MM:SSZ
 */
export const UI_BUILD_TIME_UTC: string = '${uiBuildTimeUtc}';

/**
 * Application version from package.json
 * Format: semver (e.g., "2.14.0")
 */
export const UI_APP_VERSION: string = '${uiAppVersion}';

/**
 * Build identity marker for console logs and error reports
 * Format: [UI_BUILD_IDENTITY] {values}
 */
export const BUILD_IDENTITY_MARKER = {
  marker: '[UI_BUILD_IDENTITY]',
  uiGitSha: UI_GIT_SHA,
  uiGitShaShort: UI_GIT_SHA_SHORT,
  uiBuildTimeUtc: UI_BUILD_TIME_UTC,
  uiAppVersion: UI_APP_VERSION,
} as const;

/**
 * Render human-readable build identity for display
 * @example "Build: 62355cb | 2026-02-02T06:24:54Z"
 */
export function formatBuildIdentity(): string {
  return \`Build: \${UI_GIT_SHA_SHORT} | \${UI_BUILD_TIME_UTC}\`;
}
`;

  ensureOutputDir();
  fs.writeFileSync(OUTPUT_FILE, content, 'utf8');

  console.log('[UI_BUILD_IDENTITY_GEN] Generated successfully');
  console.log(`  UI_GIT_SHA: ${uiGitSha}`);
  console.log(`  UI_GIT_SHA_SHORT: ${uiGitShaShort}`);
  console.log(`  UI_BUILD_TIME_UTC: ${uiBuildTimeUtc}`);
  console.log(`  UI_APP_VERSION: ${uiAppVersion}`);
  console.log(`  Output: ${OUTPUT_FILE}`);
}

generateBuildIdentity();
