#!/usr/bin/env node
/**
 * gen_ui_build_meta.mjs
 *
 * Generates ui_build_meta.ts with immutable UI build identifiers.
 * Called by npm prebuild to ensure UI_BUILD_SHA and UI_BUILD_TIME_UTC are always current.
 *
 * Output: atlassian/forge-app/src/gadget-ui/src/ui_build_meta.ts
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

// Compute build identifiers
function getSha7() {
  try {
    const sha = execSync('git rev-parse --short=7 HEAD', { cwd: process.cwd(), encoding: 'utf8' }).trim();
    if (!sha || sha.length === 0) {
      console.error('ERROR: git rev-parse returned empty SHA');
      process.exit(1);
    }
    return sha;
  } catch (e) {
    console.error('ERROR: Failed to get git SHA:', e.message);
    process.exit(1);
  }
}

function getTimeUtc() {
  const now = new Date();
  return now.toISOString();
}

function main() {
  const sha7 = getSha7();
  const timeUtc = getTimeUtc();

  // Ensure output directory exists
  // Script runs from atlassian/forge-app directory
  const outputDir = path.join(process.cwd(), 'src/gadget-ui/src');
  const outputFile = path.join(outputDir, 'ui_build_meta.ts');

  if (!fs.existsSync(outputDir)) {
    console.error(`ERROR: Output directory not found: ${outputDir}`);
    process.exit(1);
  }

  // Generate file content
  const content = `/**
 * ui_build_meta.ts - AUTO-GENERATED
 * 
 * Immutable UI build identifiers generated at build time.
 * DO NOT EDIT MANUALLY - regenerated by tools/gen_ui_build_meta.mjs
 */

export const UI_BUILD_SHA = "${sha7}";
export const UI_BUILD_TIME_UTC = "${timeUtc}";
`;

  // Write file
  fs.writeFileSync(outputFile, content, 'utf8');
  console.log(`✓ Generated ${outputFile}`);
  console.log(`  SHA: ${sha7}`);
  console.log(`  TIME: ${timeUtc}`);
}

main();
