#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SHA="$(git rev-parse --short=12 HEAD)"
TS_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

OUT="src/shared/build_meta.ts"
cat > "$OUT" <<EOF
/**
 * build_meta.ts
 * Single source of truth for build identity.
 * Auto-generated by tools/gen_build_meta.sh. Do not edit manually.
 */
export const FT_BUILD_SHA: string = "${SHA}";
export const FT_BUILD_TIME_UTC: string = "${TS_UTC}";
EOF

echo "WROTE $OUT SHA=$SHA TIME=$TS_UTC"
