/**
 * ui_build_meta.ts - AUTO-GENERATED
 * 
 * Immutable UI build identifiers generated at build time.
 * DO NOT EDIT MANUALLY - regenerated by tools/gen_ui_build_meta.mjs
 * 
 * CRITICAL: These values are sourced from tools/.build_meta.json (build_meta.mjs output),
 * NOT recomputed. This ensures consistency across the entire build pipeline.
 */

export const UI_GIT_SHA = "ba05cd65f372db650789ee59815783a757ef6617";
export const UI_GIT_TIME = "2026-01-24T09:05:52Z";
// Backward compatibility alias for vite.config.ts and main.ts
export const UI_BUILD_TIME_UTC = "2026-01-24T09:05:52Z";

/**
 * Dynamic marker for cache-busting: proves the UI was redeployed
 * Format: UI_MARKER_<YYYYMMDDTHHMMSSZ>_<first-7-chars-of-SHA>
 */
function getUTCTimestampForMarker(): string {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(now.getUTCDate()).padStart(2, '0');
  const hh = String(now.getUTCHours()).padStart(2, '0');
  const min = String(now.getUTCMinutes()).padStart(2, '0');
  const ss = String(now.getUTCSeconds()).padStart(2, '0');
  return `${yyyy}${mm}${dd}T${hh}${min}${ss}Z`;
}
export const UI_BUILD_MARKER = `UI_MARKER_${getUTCTimestampForMarker()}_${UI_GIT_SHA.substring(0, 7)}`;
