/**
 * ui_build_meta.ts - AUTO-GENERATED
 * 
 * Immutable UI build identifiers generated at build time.
 * DO NOT EDIT MANUALLY - regenerated by tools/gen_ui_build_meta.mjs
 */

export const UI_BUILD_SHA = "62a9b11";
export const UI_BUILD_TIME_UTC = "2026-01-16T09:43:40.080Z";
