/**
 * UI Identity - Strict contract enforcement
 * 
 * CONTRACT (immutable):
 * - UI_GIT_SHA: ALWAYS 40 hex chars from git rev-parse HEAD (read from ui_build_meta.ts)
 * - UI_BUNDLE_HASH: ALWAYS 7 hex chars (first 7 of app.<hash>.js filename)
 * 
 * GUARANTEE:
 * Different sources + different lengths = collision is CRYPTOGRAPHICALLY IMPOSSIBLE
 * 
 * Sources of truth:
 * - UI_GIT_SHA imported from ./ui_build_meta.ts (generated by build_meta.mjs + gen_ui_build_meta.mjs)
 * - UI_BUNDLE_HASH derived at runtime from app.<hash>.js filename
 */

import { UI_GIT_SHA, UI_BUILD_TIME_UTC } from './ui_build_meta';

export type UiIdentity = {
  ui_git_sha: string;           // 40 hex chars (full commit SHA from git rev-parse HEAD)
  ui_git_time_iso: string;      // ISO 8601 timestamp when built
  ui_bundle_hash: string;       // 7 hex chars (first 7 of app.<hash>.js filename)
  ui_entry_url: string | null;  // Full URL of the serving app.*.js
};

/**
 * VALIDATOR 1: Validate git SHA format (exactly 40 hex chars)
 */
export function isValidGitSha(sha: string): boolean {
  if (!sha || typeof sha !== 'string') return false;
  return /^[0-9a-f]{40}$/i.test(sha);
}

/**
 * VALIDATOR 2: Validate bundle hash format (exactly 7 hex chars)
 */
export function isValidBundleHash(hash: string): boolean {
  if (!hash || typeof hash !== 'string') return false;
  return /^[0-9a-f]{7}$/i.test(hash);
}

/**
 * Result of bundle hash extraction.
 * Pure data object; no throws.
 */
export interface BundleHashExtractionResult {
  hash: string;          // 7 hex chars OR 'UNAVAILABLE'
  reason: 'APP_HASH' | 'FORGE_INDEX_JS' | 'NO_MATCH';
  entryUrl: string | null;
}

/**
 * Extract bundle hash from script src attribute (PURE, TESTABLE)
 *
 * Detection precedence:
 * 1. Match pattern: app.<6-40-hex>.(js|mjs) → extract first 7 hex chars
 * 2. If any script src ends with /index.js → Forge-served bundle, hash UNAVAILABLE
 * 3. No match → hash UNAVAILABLE
 *
 * NEVER throws. Returns structured result.
 *
 * @param scriptSrcs - Array of script src strings (for testing). If omitted, reads from DOM.
 */
export function extractBundleHash(scriptSrcs?: string[]): BundleHashExtractionResult {
  let srcs: string[] = [];
  try {
    if (scriptSrcs) {
      srcs = scriptSrcs;
    } else if (typeof document !== 'undefined') {
      srcs = Array.from(document.querySelectorAll('script[src]')).map(
        s => s.getAttribute('src') || ''
      ).filter(Boolean);
    }
  } catch (e) {
    console.error('[UI_IDENTITY] Failed to read script sources:', e);
  }

  // Step 1: Try app.<hex>.(js|mjs)
  for (const src of srcs) {
    const match = src.match(/app\.([0-9a-f]{6,40})\.(js|mjs)/i);
    if (match && match[1]) {
      return {
        hash: match[1].substring(0, 7),
        reason: 'APP_HASH',
        entryUrl: src,
      };
    }
  }

  // Step 2: Detect Forge-served /index.js (no content-hash in filename)
  for (const src of srcs) {
    if (src.endsWith('/index.js') || src === 'index.js') {
      return {
        hash: 'UNAVAILABLE',
        reason: 'FORGE_INDEX_JS',
        entryUrl: src,
      };
    }
  }

  // Step 3: No match at all
  return {
    hash: 'UNAVAILABLE',
    reason: 'NO_MATCH',
    entryUrl: null,
  };
}

/**
 * Legacy wrapper — kept for backward compat.
 * @deprecated Use extractBundleHash() instead.
 */
export function extractBundleHashFromScript(): string | null {
  const result = extractBundleHash();
  return result.reason === 'APP_HASH' ? result.hash : null;
}

/**
 * Build UI identity from immutable build constants + runtime inspection
 * 
 * SOURCES (ONE source of truth each):
 * - ui_git_sha: UI_GIT_SHA imported from ./ui_build_meta.ts (not recomputed, not derived from filename)
 * - ui_bundle_hash: Derived from app.<hash>.js filename at runtime (first 7 chars always)
 * - ui_git_time_iso: UI_GIT_TIME imported from ./ui_build_meta.ts
 * 
 * FATAL ERRORS:
 * - [FATAL_UI_GIT_SHA_MISSING] if UI_GIT_SHA is not valid (not 40 hex)
 * - [FATAL_UI_BUNDLE_HASH_MISSING] if bundleHash is not valid (not 7 hex)
 * - [FATAL_UI_IDENTITY] if git_sha === bundle_hash (collision detected)
 */
export function buildUiIdentity(): UiIdentity {
  // v7.51: Use structured extractor (never throws)
  const extraction = extractBundleHash();
  console.log(
    `[UI_BUILD_IDENTITY_EARLY] ui_git_sha=${UI_GIT_SHA} (${UI_GIT_SHA.length} chars) | ` +
    `ui_bundle_hash=${extraction.hash} (reason=${extraction.reason})`
  );

  // FATAL 1: Validate git SHA format (still fatal — build system is truly broken)
  if (!isValidGitSha(UI_GIT_SHA)) {
    throw new Error(
      `[FATAL_UI_GIT_SHA_MISSING] UI_GIT_SHA is not 40 hex characters. ` +
      `Got ${UI_GIT_SHA.length} chars: "${UI_GIT_SHA}". ` +
      `This means build_meta.mjs or gen_ui_build_meta.mjs failed to inject the correct git SHA.`
    );
  }

  // v7.51: NON-FATAL bundle hash — degrade to 'UNAVAILABLE' instead of crashing
  let bundleHash = extraction.hash;
  if (extraction.reason !== 'APP_HASH') {
    // Log proof marker for observability (NOT a crash)
    console.error(
      '[FT_PROOF_UI_BUNDLE_HASH_UNAVAILABLE]',
      JSON.stringify({
        reason: extraction.reason,
        pattern: 'app.<hex>.js|mjs',
        entryUrl: extraction.entryUrl,
        href: typeof window !== 'undefined' ? window.location.href : 'unknown',
      })
    );
    bundleHash = 'UNAVAILABLE';
  } else if (!isValidBundleHash(bundleHash)) {
    // Hash was extracted but does not pass 7-hex validation — degrade
    console.error(
      '[FT_PROOF_UI_BUNDLE_HASH_UNAVAILABLE]',
      JSON.stringify({
        reason: 'INVALID_FORMAT',
        rawHash: bundleHash,
        pattern: 'app.<hex>.js|mjs',
        href: typeof window !== 'undefined' ? window.location.href : 'unknown',
      })
    );
    bundleHash = 'UNAVAILABLE';
  }

  // Collision detection (skip if UNAVAILABLE — can't collide with 40-hex SHA)
  if (bundleHash !== 'UNAVAILABLE' && UI_GIT_SHA === bundleHash) {
    throw new Error(
      `[FATAL_UI_IDENTITY] Git SHA equals bundle hash: "${UI_GIT_SHA}". ` +
      `This is IMPOSSIBLE (40 hex vs 7 hex cannot be equal). ` +
      `Indicates severe build system corruption.`
    );
  }

  // SUCCESS: Return identity (may have UNAVAILABLE bundle hash — UI still boots)
  const identity: UiIdentity = {
    ui_git_sha: UI_GIT_SHA,
    ui_git_time_iso: UI_BUILD_TIME_UTC,
    ui_bundle_hash: bundleHash,
    ui_entry_url: extraction.entryUrl,
  };

  // Log for verification
  console.log(
    `[UI_BUILD_IDENTITY_CONFIRMED] git_sha=${identity.ui_git_sha} | ` +
    `bundle_hash=${identity.ui_bundle_hash} | time=${identity.ui_git_time_iso}`
  );

  return identity;
}

/**
 * Format identity for human-readable logging
 */
export function formatUiIdentity(identity: UiIdentity): string {
  return (
    `UI_GIT_SHA=${identity.ui_git_sha} | ` +
    `UI_BUNDLE_HASH=${identity.ui_bundle_hash} | ` +
    `BUILT=${identity.ui_git_time_iso}`
  );
}

/**
 * Create identity anchor for gates to validate
 * 
 * CONTRACT:
 * - git_sha: Must be 40 hex chars (checked before entering)
 * - bundle_hash: Must be 7 hex chars (checked before entering)
 */
export function createIdentityAnchor(identity: UiIdentity): string {
  // Final validation before anchor creation
  if (!isValidGitSha(identity.ui_git_sha)) {
    throw new Error(
      `[FATAL_UI_IDENTITY_ANCHOR] Invalid git_sha format (must be 40 hex): ${identity.ui_git_sha}`
    );
  }

  // v7.51: Accept 'UNAVAILABLE' as valid bundle hash (Forge index.js serving)
  if (identity.ui_bundle_hash !== 'UNAVAILABLE' && !isValidBundleHash(identity.ui_bundle_hash)) {
    throw new Error(
      `[FATAL_UI_IDENTITY_ANCHOR] Invalid bundle_hash format (must be 7 hex or UNAVAILABLE): ${identity.ui_bundle_hash}`
    );
  }

  if (!identity.ui_git_time_iso) {
    throw new Error(`[FATAL_UI_IDENTITY_ANCHOR] Missing ui_git_time_iso`);
  }

  // Create immutable anchor: literal concatenation that appears in minified bundle
  const anchor =
    `FT_IDENTITY_ANCHOR_V1|` +
    `git=${identity.ui_git_sha.substring(0, 7)}|` +
    `bundle=${identity.ui_bundle_hash}|` +
    `time=${identity.ui_git_time_iso}`;

  return anchor;
}
