/**
 * UI Identity - Strict contract enforcement
 * 
 * CONTRACT (immutable):
 * - UI_GIT_SHA: ALWAYS 40 hex chars from git rev-parse HEAD (read from ui_build_meta.ts)
 * - UI_BUNDLE_HASH: ALWAYS 7 hex chars (first 7 of app.<hash>.js filename)
 * 
 * GUARANTEE:
 * Different sources + different lengths = collision is CRYPTOGRAPHICALLY IMPOSSIBLE
 * 
 * Sources of truth:
 * - UI_GIT_SHA imported from ./ui_build_meta.ts (generated by build_meta.mjs + gen_ui_build_meta.mjs)
 * - UI_BUNDLE_HASH derived at runtime from app.<hash>.js filename
 */

import { UI_GIT_SHA, UI_BUILD_TIME_UTC } from './ui_build_meta';

export type UiIdentity = {
  ui_git_sha: string;           // 40 hex chars (full commit SHA from git rev-parse HEAD)
  ui_git_time_iso: string;      // ISO 8601 timestamp when built
  ui_bundle_hash: string;       // 7 hex chars (first 7 of app.<hash>.js filename)
  ui_entry_url: string | null;  // Full URL of the serving app.*.js
};

/**
 * VALIDATOR 1: Validate git SHA format (exactly 40 hex chars)
 */
export function isValidGitSha(sha: string): boolean {
  if (!sha || typeof sha !== 'string') return false;
  return /^[0-9a-f]{40}$/i.test(sha);
}

/**
 * VALIDATOR 2: Validate bundle hash format (exactly 7 hex chars)
 */
export function isValidBundleHash(hash: string): boolean {
  if (!hash || typeof hash !== 'string') return false;
  return /^[0-9a-f]{7}$/i.test(hash);
}

/**
 * Extract bundle hash from script src attribute
 * 
 * CONTRACT:
 * - Match pattern: app.<6-40-hex>.(js|mjs)
 * - Extract hash, then ALWAYS return first 7 characters
 * - This ensures bundleHash is always 7 hex (different from 40-char git SHA)
 * 
 * Returns null if pattern not found (fatal error path will handle)
 */
export function extractBundleHashFromScript(): string | null {
  try {
    const scripts = document.querySelectorAll('script[type="module"][src]');
    for (const script of scripts) {
      const src = script.getAttribute('src') || '';
      const match = src.match(/app\.([0-9a-f]{6,40})\.(js|mjs)/i);
      if (match && match[1]) {
        // CRITICAL: Always return FIRST 7 chars for consistency
        return match[1].substring(0, 7);
      }
    }
  } catch (e) {
    console.error('[UI_IDENTITY] Failed to extract bundle hash from script:', e);
  }
  return null;
}

/**
 * Build UI identity from immutable build constants + runtime inspection
 * 
 * SOURCES (ONE source of truth each):
 * - ui_git_sha: UI_GIT_SHA imported from ./ui_build_meta.ts (not recomputed, not derived from filename)
 * - ui_bundle_hash: Derived from app.<hash>.js filename at runtime (first 7 chars always)
 * - ui_git_time_iso: UI_GIT_TIME imported from ./ui_build_meta.ts
 * 
 * FATAL ERRORS:
 * - [FATAL_UI_GIT_SHA_MISSING] if UI_GIT_SHA is not valid (not 40 hex)
 * - [FATAL_UI_BUNDLE_HASH_MISSING] if bundleHash is not valid (not 7 hex)
 * - [FATAL_UI_IDENTITY] if git_sha === bundle_hash (collision detected)
 */
export function buildUiIdentity(): UiIdentity {
  // Early marker for debugging
  const earlyBundleHash = extractBundleHashFromScript();
  console.log(
    `[UI_BUILD_IDENTITY_EARLY] ui_git_sha=${UI_GIT_SHA} (${UI_GIT_SHA.length} chars) | ` +
    `ui_bundle_hash=${earlyBundleHash} (${earlyBundleHash ? earlyBundleHash.length : 0} chars)`
  );

  // FATAL 1: Validate git SHA format
  if (!isValidGitSha(UI_GIT_SHA)) {
    throw new Error(
      `[FATAL_UI_GIT_SHA_MISSING] UI_GIT_SHA is not 40 hex characters. ` +
      `Got ${UI_GIT_SHA.length} chars: "${UI_GIT_SHA}". ` +
      `This means build_meta.mjs or gen_ui_build_meta.mjs failed to inject the correct git SHA.`
    );
  }

  // FATAL 2: Extract and validate bundle hash
  const bundleHash = extractBundleHashFromScript();
  if (!bundleHash) {
    throw new Error(
      `[FATAL_UI_BUNDLE_HASH_MISSING] Could not extract bundle hash from app.*.js script tag. ` +
      `Searched for pattern: app.<6-40-hex>.(js|mjs)`
    );
  }

  if (!isValidBundleHash(bundleHash)) {
    throw new Error(
      `[FATAL_UI_BUNDLE_HASH_MISSING] Bundle hash is not 7 hex characters. ` +
      `Got ${bundleHash.length} chars: "${bundleHash}". ` +
      `This means the filename-based cache-buster is not working correctly.`
    );
  }

  // FATAL 3: Collision detection (should be impossible, but defensive check)
  if (UI_GIT_SHA === bundleHash) {
    throw new Error(
      `[FATAL_UI_IDENTITY] Git SHA equals bundle hash: "${UI_GIT_SHA}". ` +
      `This is IMPOSSIBLE (40 hex vs 7 hex cannot be equal). ` +
      `Indicates severe build system corruption.`
    );
  }

  // Find the entry URL for identity tracking
  let entryUrl: string | null = null;
  try {
    const script = Array.from(document.querySelectorAll('script[type="module"][src]')).find(s => {
      const src = s.getAttribute('src') || '';
      return src.match(/app\.[0-9a-f]+\.(js|mjs)/i);
    });
    if (script) {
      entryUrl = script.getAttribute('src');
    }
  } catch (e) {
    console.warn('[UI_IDENTITY] Could not determine entry URL:', e);
  }

  // SUCCESS: Return validated identity
  const identity: UiIdentity = {
    ui_git_sha: UI_GIT_SHA,
    ui_git_time_iso: UI_BUILD_TIME_UTC,
    ui_bundle_hash: bundleHash,
    ui_entry_url: entryUrl,
  };

  // Log for verification
  console.log(
    `[UI_BUILD_IDENTITY_CONFIRMED] git_sha=${identity.ui_git_sha} | ` +
    `bundle_hash=${identity.ui_bundle_hash} | time=${identity.ui_git_time_iso}`
  );

  return identity;
}

/**
 * Format identity for human-readable logging
 */
export function formatUiIdentity(identity: UiIdentity): string {
  return (
    `UI_GIT_SHA=${identity.ui_git_sha} | ` +
    `UI_BUNDLE_HASH=${identity.ui_bundle_hash} | ` +
    `BUILT=${identity.ui_git_time_iso}`
  );
}

/**
 * Create identity anchor for gates to validate
 * 
 * CONTRACT:
 * - git_sha: Must be 40 hex chars (checked before entering)
 * - bundle_hash: Must be 7 hex chars (checked before entering)
 */
export function createIdentityAnchor(identity: UiIdentity): string {
  // Final validation before anchor creation
  if (!isValidGitSha(identity.ui_git_sha)) {
    throw new Error(
      `[FATAL_UI_IDENTITY_ANCHOR] Invalid git_sha format (must be 40 hex): ${identity.ui_git_sha}`
    );
  }

  if (!isValidBundleHash(identity.ui_bundle_hash)) {
    throw new Error(
      `[FATAL_UI_IDENTITY_ANCHOR] Invalid bundle_hash format (must be 7 hex): ${identity.ui_bundle_hash}`
    );
  }

  if (!identity.ui_git_time_iso) {
    throw new Error(`[FATAL_UI_IDENTITY_ANCHOR] Missing ui_git_time_iso`);
  }

  // Create immutable anchor: literal concatenation that appears in minified bundle
  const anchor =
    `FT_IDENTITY_ANCHOR_V1|` +
    `git=${identity.ui_git_sha.substring(0, 7)}|` +
    `bundle=${identity.ui_bundle_hash}|` +
    `time=${identity.ui_git_time_iso}`;

  return anchor;
}
