/**
 * build_meta.ts
 * Single source of truth for build identity.
 * Auto-generated by tools/gen_build_meta.sh. Do not edit manually.
 */
export const FT_BUILD_SHA = "01ae4b8ecec9";
export const FT_BUILD_TIME_UTC = "2026-01-15T09:59:11Z";
