/**
 * build_meta.ts
 * Single source of truth for build identity.
 * Auto-generated by tools/gen_build_meta.sh. Do not edit manually.
 */
export const FT_BUILD_SHA = "4062fc6f7e9a";
export const FT_BUILD_TIME_UTC = "2026-01-15T09:16:27Z";
