/**
 * build_meta.ts
 * Single source of truth for build identity.
 * Auto-generated by tools/gen_build_meta.sh. Do not edit manually.
 */
export const FT_BUILD_SHA: string = "4688c2ae9503";
export const FT_BUILD_TIME_UTC: string = "2026-01-15T10:24:02Z";
