#!/usr/bin/env bash
# Marketplace report defensibility gates
# Blocks commits if report contains:
# - Local /tmp or filesystem paths (not reproducible in CI)
# - Stale freeze narrative (misaligned with verify_freeze_lock.sh)
# - Unknown evidence file references (not in CI generation spec)

set -euo pipefail
export LC_ALL=C
export LANG=C

REPORT="docs/MARKETPLACE_READINESS_REPORT.md"

fail() { echo "FAIL: $1"; exit 1; }

test -f "$REPORT" || fail "REPORT_MISSING"

echo "=== Marketplace Report Defensibility Checks ==="

# 1) Ban local evidence tokens anywhere
if rg -n "/tmp/|ft_full_proof|ft_atomic" "$REPORT" -S 2>/dev/null; then
  fail "LOCAL_EVIDENCE_TOKENS_PRESENT: /tmp paths, ft_full_proof, or ft_atomic not allowed"
fi
echo "✓ No /tmp or local filesystem paths"

# 2) Ban stale freeze narrative text
if rg -n "exits with code 1|HEAD~1|payload commit|previous commit" "$REPORT" -S 2>/dev/null; then
  fail "STALE_FREEZE_NARRATIVE: report describes old freeze verification logic"
fi
echo "✓ No stale freeze narrative"

# 3) Require CI artifact language
if ! rg -n "CI artifact|marketplace-proof-|Evidence Availability" "$REPORT" -S 2>/dev/null; then
  fail "MISSING_CI_ARTIFACT_LANGUAGE: must mention CI artifacts or marketplace-proof"
fi
echo "✓ CI artifact language present"

# 4) Evidence filename integrity check
# Extract every NN_something.txt referenced and verify it's in the KNOWN list
echo "Checking evidence file references..."

EVID=$(python3 - <<'PYEOF'
import re, pathlib
txt = pathlib.Path("docs/MARKETPLACE_READINESS_REPORT.md").read_text()
files = sorted(set(re.findall(r'`(\d{2}_[^`]+?\.txt)`', txt)))
print("\n".join(files))
PYEOF
)

# Known evidence files generated by tools/generate_ci_evidence.sh
KNOWN=$(cat <<'EOF'
00_baseline.txt
01_repo_map.txt
01_feature_inventory.txt
02_npm_ci.txt
02_tests.txt
02_build.txt
02_typecheck.txt
02_forge_version.txt
02_forge_lint.txt
03_credential_scan.txt
04_scopes_and_usage.txt
04_write_ops_scan.txt
04_admin_post_context.txt
04_egress_scan.txt
05_freeze_generate.txt
05_freeze_verify_1.txt
05_freeze_verify_2.txt
06_validate_docs.txt
EOF
)

# Check each referenced evidence file is known
while read -r f; do
  [ -z "$f" ] && continue
  if ! echo "$KNOWN" | rg -qx "$f"; then
    fail "UNKNOWN_EVIDENCE_FILE_REFERENCED: $f (not in CI generation spec)"
  fi
done <<< "$EVID"

echo "✓ All evidence files are from CI generation spec"

echo ""
echo "✅ OK: Marketplace report is defensible"
exit 0
