/**
 * ui_build_meta.ts - AUTO-GENERATED
 * 
 * Immutable UI build identifiers generated at build time.
 * DO NOT EDIT MANUALLY - regenerated by tools/gen_ui_build_meta.mjs
 * 
 * CRITICAL: These values are sourced from tools/.build_meta.json (build_meta.mjs output),
 * NOT recomputed. This ensures consistency across the entire build pipeline.
 */

export const UI_GIT_SHA = "613fb705d58d70101c16b549dfac2b73a69dea61";
export const UI_GIT_TIME = "2026-02-10T09:47:37Z";
// Backward compatibility alias for vite.config.ts and main.ts
export const UI_BUILD_TIME_UTC = "2026-02-10T09:47:37Z";

/**
 * Deterministic cache-buster marker derived from git commit time (NOT wall-clock)
 * Format: UI_MARKER_<YYYYMMDDTHHMMSSZ>_<first-7-chars-of-SHA>
 * Time is extracted from UI_GIT_TIME (immutable commit time), not generated at runtime.
 */
export const UI_BUILD_MARKER = `UI_MARKER_20260210T094737Z_${UI_GIT_SHA.substring(0, 7)}`;
