/**
 * AUTO-GENERATED BUILD METADATA
 * Do not edit manually. Generated by tools/gen_build_meta.mjs
 *
 * DETERMINISTIC: Sourced from git commit metadata only (no runtime clocks)
 *
 * Sources:
 * - HEAD12: 8127c76ee8ea
 * - COMMIT_TIME: 2026-01-17T10:22:37.000Z (git commit timestamp, %cI normalized to .000Z)
 * - TREE_HASH: fc5982cd6c25f55d1d30e58efe1924cd645f7452 (git tree hash, immutable per commit state)
 *
 * Running generator twice on same commit MUST produce byte-identical files.
 */

export const FT_BUILD_SHA = "8127c76ee8ea";export const FT_BUILD_COMMIT_TIME = "2026-01-17T10:22:37.000Z";export const FT_BUILD_TREE_HASH = "fc5982cd6c25f55d1d30e58efe1924cd645f7452";

 // Backward compatibility: old names for the same values
export const FT_BUILD_TIME_UTC = FT_BUILD_COMMIT_TIME;
export const UI_BUILD_SHA = FT_BUILD_SHA;
export const UI_BUILD_TIME_UTC = FT_BUILD_COMMIT_TIME;
