#!/usr/bin/env bash
set -euo pipefail

# Source common utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/_common.sh
source "${SCRIPT_DIR}/_common.sh"

run_evidence_hash_pack() {
  local evidence_root="$1"
  local audit_dir="${evidence_root}/09_evidence_pack"

  log_info "Starting evidence hash pack generation..."
  mkdir -p "$audit_dir"

  # Initialize evidence tracking
  local evidence_files=()
  local total_files=0
  local hash_failures=0
  local pack_status="PASS"

  # Find all evidence files with type classification
  while IFS= read -r -d '' file; do
    [[ -f "$file" ]] || continue

    local relative_path="${file#"$evidence_root"/}"

    # Skip our own evidence pack directory
    [[ "$relative_path" == 09_evidence_pack/* ]] && continue

    evidence_files+=("$file")
    ((total_files++))

  done < <(find "$evidence_root" -type f \( -name "*.json" -o -name "*.txt" -o -name "*.md" -o -name "*.sha256" \) -print0 2>/dev/null)

  log_info "Found $total_files evidence files to hash"

  # Function to determine file type
  classify_file_type() {
    local path="$1"
    case "$path" in
      08_governance_snapshot/raw/*)
        echo "raw"
        ;;
      08_governance_snapshot/canonical/*)
        echo "canonical"
        ;;
      08_governance_snapshot/derived/*)
        echo "derived"
        ;;
      08_governance_snapshot/validation/*)
        echo "validation"
        ;;
      00_meta/*)
        echo "meta"
        ;;
      *)
        echo "evidence"
        ;;
    esac
  }

  # Generate file manifest with hashes and types
  local manifest_entries=()
  local manifest_json_entries=()
  local timestamp
  timestamp=$(create_timestamp)

  # Calculate SHA256 for each evidence file
  for file in "${evidence_files[@]}"; do
    local relative_path="${file#"$evidence_root"/}"
    local file_hash file_size file_type

    if file_hash=$(sha256sum "$file" 2>/dev/null | cut -d' ' -f1); then
      file_size=$(stat -c%s "$file" 2>/dev/null || echo "0")
      file_type=$(classify_file_type "$relative_path")

      log_info "✓ Hashed: $relative_path"

      # Add to JSON manifest
      manifest_json_entries+=("{\"path\":\"$relative_path\",\"bytes\":$file_size,\"sha256\":\"$file_hash\",\"type\":\"$file_type\"}")

      # Add to text manifest entries (sorted order for determinism)
      manifest_entries+=("$file_hash  $relative_path")

    else
      log_error "✗ Failed to hash: $relative_path"
      ((hash_failures++))
      pack_status="FAIL"
    fi
  done

  # Sort entries for deterministic output
  IFS=$'\n' manifest_entries=($(sort <<<"${manifest_entries[*]}"))

  # Write JSON evidence manifest
  local manifest_json
  manifest_json=$(jq -n \
    --arg timestamp "$timestamp" \
    --arg evidence_root "$evidence_root" \
    --argjson files "$(printf '[%s]' "$(IFS=,; echo "${manifest_json_entries[*]}")")" \
    '{
      generated_at_utc: $timestamp,
      evidence_root: $evidence_root,
      files: $files
    }')

  echo "$manifest_json" > "${audit_dir}/evidence_manifest.json"

  # Write SHA256 hash manifest (traditional format)
  {
    echo "# Evidence Hash Manifest"
    echo "# Generated: $timestamp"
    echo "# Total files: $total_files"
    echo "# Hash failures: $hash_failures"
    echo ""
    for entry in "${manifest_entries[@]}"; do
      echo "$entry"
    done
  } > "${audit_dir}/evidence_manifest.sha256"

  # Generate PROOF_PACK_SHA256.txt (hash of the manifest)
  local manifest_hash
  if manifest_hash=$(sha256sum "${audit_dir}/evidence_manifest.sha256" 2>/dev/null | cut -d' ' -f1); then
    echo "$manifest_hash" > "${audit_dir}/PROOF_PACK_SHA256.txt"
    log_info "✓ Generated proof pack hash: $manifest_hash"
  else
    log_error "✗ Failed to generate proof pack hash"
    ((hash_failures++))
    pack_status="FAIL"
  fi

  # Generate evidence pack summary
  cat > "${audit_dir}/evidence_pack_summary.json" << EOF
{
  "timestamp": "$timestamp",
  "evidence_root": "$evidence_root",
  "pack_status": "$pack_status",
  "total_files": $total_files,
  "hash_failures": $hash_failures,
  "manifest_files": [
    "evidence_manifest.json",
    "evidence_manifest.sha256",
    "PROOF_PACK_SHA256.txt"
  ],
  "proof_pack_hash": "${manifest_hash:-null}"
}
EOF

  # Generate verification instructions
  cat > "${audit_dir}/VERIFICATION_INSTRUCTIONS.md" << EOF
# Provable Evidence Pack Verification Instructions

This evidence pack contains cryptographic hashes of all governance evidence files generated by FirstTry's provable evidence pipeline.

## Verification Steps

### 1. Verify Evidence Manifest Hash
\`\`\`bash
sha256sum -c evidence_manifest.sha256
\`\`\`

### 2. Verify Proof Pack Hash
\`\`\`bash
# Verify the hash of the evidence manifest itself
expected=\$(cat PROOF_PACK_SHA256.txt)
actual=\$(sha256sum evidence_manifest.sha256 | cut -d' ' -f1)
[[ "\$expected" == "\$actual" ]] && echo "PROOF PACK VERIFIED" || echo "PROOF PACK FAILED"
\`\`\`

### 3. Verify Raw → Canonical → Derived Chain
\`\`\`bash
# Verify that canonical files are derived from raw files
# and derived files reference canonical inputs correctly
jq '.files[] | select(.type=="derived") | .path' evidence_manifest.json
\`\`\`

### 4. Verify Validation Assertions
\`\`\`bash
# Check validation report assertions
jq '.files[] | select(.type=="validation")' evidence_manifest.json
\`\`\`

## Evidence Integrity

- **Total Evidence Files:** $total_files
- **Hash Algorithm:** SHA256
- **Provenance Chain:** Raw → Canonical → Derived → Validation
- **Verification Status:** $pack_status

## Generated by

**FirstTry – Provable Governance Evidence for Jira Cloud**

All evidence is cryptographically verifiable with complete provenance from raw Jira API responses.
EOF

  # Determine return status
  if [[ "$pack_status" == "PASS" ]]; then
    log_success "Evidence hash pack generated successfully"
    log_info "Total files hashed: $total_files"
    log_info "Hash failures: $hash_failures"
    return 0
  else
    log_error "Evidence hash pack generation failed: $hash_failures hash failures"
    return 1
  fi
}

# Only execute if run directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  run_evidence_hash_pack "${1:-}" || exit $?
fi